---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
  - package-ecosystem: "npm"
    directory: "/antora"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
  - package-ecosystem: "gomod"
    directory: "/website"
    schedule:
      interval: weekly
      time: '15:00'
      timezone: Etc/UTC
